### ISSUE TITLE
Note to self about version 2.0

### ISSUE THREAD

**Issue by LTLA** [LTLA/bakana#40]
- [x] Remove `summary()`; document the other getters properly, and allow applications to define their own callbacks for each step. This should provide more flexibility for applications to decide what messages they want to receive. (#41)
- [x] Deciding which modality names correspond to ADT, RNA, etc. should be the responsibility of each `Dataset` class. This eliminates the guessing step (though it is likely that we'll have to keep that around somewhere for back-compatibility). (#42)
- [x] Deciding which assay to use for the RDS reader should be a user-modifiable parameter, rather than a guess. (#42)
- [x] Deciding which row identifiers to use for combining multiple matrices should be a parameter in ~`InputsState#compute`~ each reader. (#42)
- [x] Add some options to normalize + do some DE on CRISPR ~and ATAC-seq~ data, I suppose. (#47)
